# Generated by Django 4.0.3 on 2022-03-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lecture_id_remove_video_lecture_lecture_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='files',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='lecture',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.lecture'),
            preserve_default=False,
        ),
    ]
