# Generated by Django 4.0.3 on 2022-03-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_video_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='LectureVideo',
        ),
    ]
