# Generated by Django 4.0.3 on 2022-03-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_newid_newimage_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newimage',
            old_name='ItemId',
            new_name='itemId',
        ),
    ]
