# Generated by Django 4.0.3 on 2022-03-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_itemid_newimage_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturevideo',
            old_name='lecture',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='newimage',
            old_name='itemId',
            new_name='item',
        ),
    ]
