# Generated by Django 4.0.3 on 2022-04-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='files',
        ),
    ]
