# Generated by Django 4.0.3 on 2022-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_status_statusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
