# Generated by Django 4.0.3 on 2022-04-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_image_created_at_image_updated_at_alter_bookpdf_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='desc',
        ),
    ]
