# Generated by Django 4.0.3 on 2022-04-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_liveyoutube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveyoutube',
            old_name='value',
            new_name='url',
        ),
    ]
