# Generated by Django 4.0.3 on 2022-04-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_value_liveyoutube_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveYoutube',
            new_name='Live',
        ),
    ]
