# Generated by Django 4.0.3 on 2022-04-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_help_helpimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpdf',
            name='color',
        ),
    ]
