# Generated by Django 4.0.3 on 2022-04-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_aidchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AidChart',
        ),
    ]
