# Generated by Django 4.0.3 on 2022-04-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_help_source_help_type_help_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='source',
            field=models.CharField(choices=[('I', 'Imam hussain holy shrain'), ('S', 'Sharia rights')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='help',
            name='type',
            field=models.CharField(choices=[('MG', 'Marriage aid'), ('B', 'Building aid'), ('D', 'Pay off debts'), ('O', 'Other'), ('MD', 'Medical aid'), ('R', 'Reduction of pays'), ('P', 'Paying the rent')], default='O', max_length=2),
        ),
    ]
