# Generated by Django 4.0.3 on 2022-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_help_source_alter_help_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridaysermonvideo',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='fridaysermonvideo',
            name='video_2',
        ),
        migrations.AddField(
            model_name='fridaysermon',
            name='video_1',
            field=models.URLField(default='http://dj.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridaysermon',
            name='video_2',
            field=models.URLField(default='http://dj.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fridaysermon',
            name='desc_1',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fridaysermon',
            name='desc_2',
            field=models.CharField(max_length=1000000),
        ),
    ]
