# Generated by Django 4.0.3 on 2022-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_fridaysermonvideo_video_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturevideo',
            name='video',
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.URLField(default='http://jdasf.com', max_length=500),
            preserve_default=False,
        ),
    ]
