# Generated by Django 4.0.3 on 2022-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_lecturevideo_video_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='type',
            field=models.CharField(choices=[('MG', 'Marriage aid'), ('B', 'Building aid'), ('D', 'Pay off debts'), ('O', 'Other'), ('MD', 'Medical aid'), ('R', 'Reduction of pays'), ('P', 'Paying the rent'), ('F', 'Feed and clothe')], default='O', max_length=2),
        ),
    ]
