# Generated by Django 4.0.3 on 2022-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_help_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='desc',
            field=models.CharField(max_length=10000),
        ),
    ]
